# Generated by Django 3.1.2 on 2020-10-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='people_count',
        ),
        migrations.AddField(
            model_name='rates',
            name='people_count',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
