# Generated by Django 3.1.2 on 2020-10-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0002_auto_20201029_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='people_count',
            field=models.IntegerField(default='0'),
        ),
    ]
